name: Update Latest Image

on:
  push:
    paths:
      - "images/*"

jobs:
  update-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Find Latest Image and Rename
        run: |
          latest_file=$(ls -t images/*.png | head -n 1)
          cp "$latest_file" images/latest.png
          echo "Latest file copied: $latest_file"

      - name: Commit and Push Changes
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          git add images/latest.png
          git commit -m "Update latest image" || echo "No changes to commit"
          git push

      - name: Force GitHub Pages Update
        run: |
          git commit --allow-empty -m "Trigger GitHub Pages update"
          git push
